name: Translate React Intl messages

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  translate-react-intl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: doloc-io/doloc-action@v1
        with:
          token: ${{ secrets.DOLOC_API_TOKEN }}
          source: src/lang/en.json
          targets: |
            src/lang/de.json:de
            src/lang/fr.json:fr
